package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1



/**
 * Otherdrain generated by hbm2java
 */
public class Otherdrain  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private double arend;
     private double service;

    public Otherdrain() {
    }

    public Otherdrain(Project project, double arend, double service) {
       this.project = project;
       this.arend = arend;
       this.service = service;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public double getArend() {
        return this.arend;
    }
    
    public void setArend(double arend) {
        this.arend = arend;
    }
    public double getService() {
        return this.service;
    }
    
    public void setService(double service) {
        this.service = service;
    }




}


