package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1


/**
 * Projectgroup generated by hbm2java
 */
public class Projectgroup  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;

    public Projectgroup() {
    }

	
    public Projectgroup(User user, String name) {
        this.user = user;
        this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}


