package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1


/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private Integer id;
     private Projectgroup projectgroup;
     private String name;

    public Project() {
    }

	
    public Project(Projectgroup projectgroup, String name) {
        this.projectgroup = projectgroup;
        this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Projectgroup getProjectgroup() {
        return this.projectgroup;
    }
    
    public void setProjectgroup(Projectgroup projectgroup) {
        this.projectgroup = projectgroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}


