package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1



/**
 * Promotion generated by hbm2java
 */
public class Promotion  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private double releaseAll;
     private double supportIndayStart;
     private double multiplierInday;
     private int companyDays;

    public Promotion() {
    }

    public Promotion(Project project, double releaseAll, double supportIndayStart, double multiplierInday, int companyDays) {
       this.project = project;
       this.releaseAll = releaseAll;
       this.supportIndayStart = supportIndayStart;
       this.multiplierInday = multiplierInday;
       this.companyDays = companyDays;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public double getReleaseAll() {
        return this.releaseAll;
    }
    
    public void setReleaseAll(double releaseAll) {
        this.releaseAll = releaseAll;
    }
    public double getSupportIndayStart() {
        return this.supportIndayStart;
    }
    
    public void setSupportIndayStart(double supportIndayStart) {
        this.supportIndayStart = supportIndayStart;
    }
    public double getMultiplierInday() {
        return this.multiplierInday;
    }
    
    public void setMultiplierInday(double multiplierInday) {
        this.multiplierInday = multiplierInday;
    }
    public int getCompanyDays() {
        return this.companyDays;
    }
    
    public void setCompanyDays(int companyDays) {
        this.companyDays = companyDays;
    }




}


