package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1



/**
 * Quality generated by hbm2java
 */
public class Quality  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private byte gui;
     private byte functional;
     private byte actuality;
     private byte support;
     private byte speed;
     private byte hardware;

    public Quality() {
    }

    public Quality(Project project, byte gui, byte functional, byte actuality, byte support, byte speed, byte hardware) {
       this.project = project;
       this.gui = gui;
       this.functional = functional;
       this.actuality = actuality;
       this.support = support;
       this.speed = speed;
       this.hardware = hardware;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public byte getGui() {
        return this.gui;
    }
    
    public void setGui(byte gui) {
        this.gui = gui;
    }
    public byte getFunctional() {
        return this.functional;
    }
    
    public void setFunctional(byte functional) {
        this.functional = functional;
    }
    public byte getActuality() {
        return this.actuality;
    }
    
    public void setActuality(byte actuality) {
        this.actuality = actuality;
    }
    public byte getSupport() {
        return this.support;
    }
    
    public void setSupport(byte support) {
        this.support = support;
    }
    public byte getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(byte speed) {
        this.speed = speed;
    }
    public byte getHardware() {
        return this.hardware;
    }
    
    public void setHardware(byte hardware) {
        this.hardware = hardware;
    }




}


