package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1



/**
 * Sales generated by hbm2java
 */
public class Sales  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private int planningPaybackIndays;
     private double planningPayback;
     private int planningAuditory;
     private double costForoneRelease;
     private double costForoneOther;

    public Sales() {
    }

    public Sales(Project project, int planningPaybackIndays, double planningPayback, int planningAuditory, double costForoneRelease, double costForoneOther) {
       this.project = project;
       this.planningPaybackIndays = planningPaybackIndays;
       this.planningPayback = planningPayback;
       this.planningAuditory = planningAuditory;
       this.costForoneRelease = costForoneRelease;
       this.costForoneOther = costForoneOther;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public int getPlanningPaybackIndays() {
        return this.planningPaybackIndays;
    }
    
    public void setPlanningPaybackIndays(int planningPaybackIndays) {
        this.planningPaybackIndays = planningPaybackIndays;
    }
    public double getPlanningPayback() {
        return this.planningPayback;
    }
    
    public void setPlanningPayback(double planningPayback) {
        this.planningPayback = planningPayback;
    }
    public int getPlanningAuditory() {
        return this.planningAuditory;
    }
    
    public void setPlanningAuditory(int planningAuditory) {
        this.planningAuditory = planningAuditory;
    }
    public double getCostForoneRelease() {
        return this.costForoneRelease;
    }
    
    public void setCostForoneRelease(double costForoneRelease) {
        this.costForoneRelease = costForoneRelease;
    }
    public double getCostForoneOther() {
        return this.costForoneOther;
    }
    
    public void setCostForoneOther(double costForoneOther) {
        this.costForoneOther = costForoneOther;
    }




}


