package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1



/**
 * Timescheduler generated by hbm2java
 */
public class Timescheduler  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private int architecture;
     private int developing;
     private int testing;
     private int release;
     private int support;

    public Timescheduler() {
    }

    public Timescheduler(Project project, int architecture, int developing, int testing, int release, int support) {
       this.project = project;
       this.architecture = architecture;
       this.developing = developing;
       this.testing = testing;
       this.release = release;
       this.support = support;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public int getArchitecture() {
        return this.architecture;
    }
    
    public void setArchitecture(int architecture) {
        this.architecture = architecture;
    }
    public int getDeveloping() {
        return this.developing;
    }
    
    public void setDeveloping(int developing) {
        this.developing = developing;
    }
    public int getTesting() {
        return this.testing;
    }
    
    public void setTesting(int testing) {
        this.testing = testing;
    }
    public int getRelease() {
        return this.release;
    }
    
    public void setRelease(int release) {
        this.release = release;
    }
    public int getSupport() {
        return this.support;
    }
    
    public void setSupport(int support) {
        this.support = support;
    }




}


