package com.smolyakovaov.hibernate;
// Generated 18.12.2014 2:18:48 by Hibernate Tools 4.3.1



/**
 * Workers generated by hbm2java
 */
public class Workers  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private int seos;
     private int architects;
     private int designers;
     private int developers;
     private int testers;
     private int supports;

    public Workers() {
    }

    public Workers(Project project, int seos, int architects, int designers, int developers, int testers, int supports) {
       this.project = project;
       this.seos = seos;
       this.architects = architects;
       this.designers = designers;
       this.developers = developers;
       this.testers = testers;
       this.supports = supports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public int getSeos() {
        return this.seos;
    }
    
    public void setSeos(int seos) {
        this.seos = seos;
    }
    public int getArchitects() {
        return this.architects;
    }
    
    public void setArchitects(int architects) {
        this.architects = architects;
    }
    public int getDesigners() {
        return this.designers;
    }
    
    public void setDesigners(int designers) {
        this.designers = designers;
    }
    public int getDevelopers() {
        return this.developers;
    }
    
    public void setDevelopers(int developers) {
        this.developers = developers;
    }
    public int getTesters() {
        return this.testers;
    }
    
    public void setTesters(int testers) {
        this.testers = testers;
    }
    public int getSupports() {
        return this.supports;
    }
    
    public void setSupports(int supports) {
        this.supports = supports;
    }




}


